travis:
  secure:
    BINSTAR_TOKEN: R+409Qkt1NDpk89UnTsSfw2hME4B0FLjfPZgJNY+INeah76CY9G7NoxFqmoNIo+UCsS+HN84mwSolopBqSPlQ8Ip7kKkzzGY8q7cN9eWZUXNQ/uCkZPijKk5XLrHXIFyqmUyhkNqIY5Pod9S33V6swnCWUDo+WKeW8h7GbAdxQ3903x54IQksRCV+CmcMZ6bGPOVMV6lpb3hKzTqvmkUakyln4mOXT2QEW+CcFLXwyodgyCXboib7TRUVyDsKb0vZ7vLpKTlQCGd4Uveuw6cGnvxblHIdjZwt0rtvmVT7iBbv3hHYEAsYf0z8020btAUf/LHkXRWnY/kF33kfwoA4BZlkbDlHzaqCw8IFXfPvEzKCnatP27WCxl6hDdThSxW+030RJhRy80ZXUBas/NQ/qr8flLiHB2DOiNy+yD9nnE2xDHR+3PuaXwxXOoFPM1jK/lYTpsdW4TxNDpZtwHezeZWAVyfYcqNCF12GeQLMY0HwiQ3cRGUotJU4UVI1trhy6FhW7vR1vy0t1g9aAE+BRlog5kiS2Up4rl1V2UAjpxDEewER8TvaaGyF09SDAAfDuixgoDP0EmZGvi7Zxh88gV0fBQbkacEymOmvR1unb1d8JXx2TPWrdHduFcmZ1wz5cRNYsJ1mBE6kJ8wwLlw03ZFEvTcQmheTViCPVQB3I4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
